// <auto-generated />
namespace Book_Store_Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class book_category : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(book_category));
        
        string IMigrationMetadata.Id
        {
            get { return "202110210947599_book_category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
