// <auto-generated />
namespace Book_Store_Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Coupon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Coupon));
        
        string IMigrationMetadata.Id
        {
            get { return "202110240558593_Coupon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
