// <auto-generated />
namespace Book_Store_Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class wishlist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(wishlist));
        
        string IMigrationMetadata.Id
        {
            get { return "202110231352499_wishlist"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
